### ISSUE TITLE
can't change to other currency in the overview charts

### ISSUE THREAD

**Issue by juliomatcom** [pRoy24/tokenplex-core#1]
Hello!
I found this I don't know if is it currently unsupported or just a bug.

Reproduce:
- Go to https://tokenplex.io/token/BTC/home
- Clic on the USD select dropdown.

thanks for the app.

**Comment by juliomatcom** [comment]
The others drop-down lists have the same issue.

**Comment by pRoy24** [comment]
Hi @juliomatcom , 
Thanks for trying the App.

The drop-downs for changing tSym are unimplemented in this beta. The strategy for storing multiple tSym items will require a little change to the models.

Hopefully will be able to implement this within the coming weeks. :)

**Comment by pRoy24** [comment]
Hi, 
You can now switch between USD and BTC, and also switch between Yearly and Weekly Graph in the coin home page view.

Candlesticks graph views is a work in progress and will try to implement soon.
https://tokenplex.io/token/ETH/home

Closing this issue as resolved.
