### ISSUE TITLE
Did the format for the GET request for details change?

### ISSUE THREAD

**Issue by andrewrains** [pRoy24/tokenplex-core#2]
https://api.tokenplex.io/coin/coin-detail?coin_symbol=BTC returns "error": "coin symbol must be specified"

**Comment by pRoy24** [comment]
Hi,
Please use https://api.tokenplex.io/coin/coin-detail?from_symbol=BTC&to_symbol=USD format.

The endpoint has been changed to acomodate multiple to_symbol currencies.
Please find updated docs at http://api.tokenplex.io/docs/

**Comment by andrewrains** [comment]
Thank you! I must not have refreshed the page as I'm now seeing other endpoints too. Very cool!
